apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-test
  labels:
    helm.sh/chart: nginx-test-0.1.0
    app.kubernetes.io/name: nginx-test
    app.kubernetes.io/instance: nginx-test
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: nginx-test/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-test
  labels:
    helm.sh/chart: nginx-test-0.1.0
    app.kubernetes.io/name: nginx-test
    app.kubernetes.io/instance: nginx-test
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: nginx-test
    app.kubernetes.io/instance: nginx-test
---
# Source: nginx-test/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  labels:
    helm.sh/chart: nginx-test-0.1.0
    app.kubernetes.io/name: nginx-test
    app.kubernetes.io/instance: nginx-test
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-test
      app.kubernetes.io/instance: nginx-test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-test
        app.kubernetes.io/instance: nginx-test
    spec:
      serviceAccountName: nginx-test
      securityContext:
        {}
      containers:
        - name: nginx-test
          securityContext:
            {}
          image: "nginx:1.16.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {}
