name: CI

on:
  push:

jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.vars.outputs.tag }}
    steps:
      - id: vars
        run: echo "::set-output name=tag::$(echo $GITHUB_SHA | cut -c 1-8)"
  build:
    runs-on: ubuntu-latest
    needs:
      - vars
    steps:
      - uses: actions/checkout@v2
      - run: echo "COMMIT_SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - run: echo "${{ needs.vars.outputs.tag}}"
      # - run: make test
      # - run: make bootstrap
      # - run: make e2e
      - run: go version
      - run: GO111MODULE=on go get github.com/mikefarah/yq/v3
      - run: PATH=$(go env GOPATH)/bin:$PATH yq write -i nginx-test.yaml metadata.name test
      - run: cat nginx-test.yaml
      - run: echo ${{ env.COMMIT_SHORT_SHA }}
      - uses: crazy-max/ghaction-dump-context@v1
