name: CI

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: COMMIT_SHORT_SHA=$(sh git rev-parse --short HEAD) >> $GITHUB_ENV
      # - run: make test
      # - run: make bootstrap
      # - run: make e2e
      - run: echo ${{ env.COMMIT_SHORT_SHA }}
