name: CI

on:
  push:
  schedule:
    - cron: '0/3 * * * *'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "COMMIT_SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      # - run: make test
      # - run: make bootstrap
      # - run: make e2e
      - run: echo ${{ env.COMMIT_SHORT_SHA }}
      - uses: crazy-max/ghaction-dump-context@v1
