name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "COMMIT_SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      # - run: make test
      # - run: make bootstrap
      # - run: make e2e
      - run: go version
      - run: GO111MODULE=on go get github.com/mikefarah/yq/v4
      - run: PATH=$(go env GOPATH)/bin:$PATH yq -i '.metadata[0].name = "test"' nginx-test.yaml
      - run: echo ${{ env.COMMIT_SHORT_SHA }}
      - uses: crazy-max/ghaction-dump-context@v1
